USE [master]
GO

/****** Object:  Database [Kutuphane]    Script Date: 7.02.2022 23:17:06 ******/
CREATE DATABASE [Kutuphane]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Kutuphane', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Kutuphane.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Kutuphane_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Kutuphane_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Kutuphane] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Kutuphane].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Kutuphane] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Kutuphane] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Kutuphane] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Kutuphane] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Kutuphane] SET ARITHABORT OFF 
GO

ALTER DATABASE [Kutuphane] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Kutuphane] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Kutuphane] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Kutuphane] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Kutuphane] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Kutuphane] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Kutuphane] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Kutuphane] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Kutuphane] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Kutuphane] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Kutuphane] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Kutuphane] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Kutuphane] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Kutuphane] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Kutuphane] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Kutuphane] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Kutuphane] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Kutuphane] SET RECOVERY FULL 
GO

ALTER DATABASE [Kutuphane] SET  MULTI_USER 
GO

ALTER DATABASE [Kutuphane] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Kutuphane] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Kutuphane] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Kutuphane] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Kutuphane] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Kutuphane] SET  READ_WRITE 
GO


