USE [Kutuphane]
GO

/****** Object:  Table [dbo].[CEVIRMENLER]    Script Date: 7.02.2022 23:19:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CEVIRMENLER](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Kitap_id] [int] NOT NULL,
	[Cevirdigi_dil] [nchar](20) NOT NULL,
	[CevirmenSoyad] [nchar](20) NOT NULL,
	[CevirmenAd] [nchar](20) NOT NULL,
 CONSTRAINT [PK_CEVIRMENLER] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CEVIRMENLER]  WITH CHECK ADD  CONSTRAINT [FK_CEVIRMENLER_KITAPLAR] FOREIGN KEY([Kitap_id])
REFERENCES [dbo].[KITAPLAR] ([Id])
GO

ALTER TABLE [dbo].[CEVIRMENLER] CHECK CONSTRAINT [FK_CEVIRMENLER_KITAPLAR]
GO


