USE [Kutuphane]
GO

/****** Object:  Table [dbo].[UYELER]    Script Date: 26.12.2021 16:07:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UYELER](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
	[Soyad] [nvarchar](50) NOT NULL,
	[Adres_id] [int] NOT NULL,
	[Cinsiyet] [nchar](10) NOT NULL,
	[Tur_id] [int] NOT NULL,
	[GSM] [nvarchar](11) NOT NULL,
 CONSTRAINT [PK_UYELER] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UYELER]  WITH CHECK ADD  CONSTRAINT [FK_UYELER_ADRESLER] FOREIGN KEY([Adres_id])
REFERENCES [dbo].[ADRESLER] ([Id])
GO

ALTER TABLE [dbo].[UYELER] CHECK CONSTRAINT [FK_UYELER_ADRESLER]
GO

ALTER TABLE [dbo].[UYELER]  WITH CHECK ADD  CONSTRAINT [FK_UYELER_TUR] FOREIGN KEY([Tur_id])
REFERENCES [dbo].[TUR] ([Id])
GO

ALTER TABLE [dbo].[UYELER] CHECK CONSTRAINT [FK_UYELER_TUR]
GO


