USE [Kutuphane]
GO

/****** Object:  Table [dbo].[YAZARLAR]    Script Date: 26.12.2021 16:08:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[YAZARLAR](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nchar](20) NOT NULL,
	[Soyad] [nchar](20) NOT NULL,
	[Kitap_id] [int] NOT NULL,
 CONSTRAINT [PK_YAZARLAR] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[YAZARLAR]  WITH CHECK ADD  CONSTRAINT [FK_YAZARLAR_KITAPLAR] FOREIGN KEY([Kitap_id])
REFERENCES [dbo].[KITAPLAR] ([Id])
GO

ALTER TABLE [dbo].[YAZARLAR] CHECK CONSTRAINT [FK_YAZARLAR_KITAPLAR]
GO


